spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/" #configserver
  codec:
    max-in-memory-size: 500MB
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: configserver-monitor
          uri: http://configserver:8071
          predicates:
            - Path=/configserver/monitor
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/finance/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "Finance Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      finance:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"