package com.finance.aiservice.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.embedding.EmbeddingModel;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Service for generating text embeddings using Spring AI EmbeddingModel.
 *
 * Uses the configured embedding model (Google text-embedding-004) to convert
 * text into vectors for semantic similarity search in RAG.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class EmbeddingService {

    private final EmbeddingModel embeddingModel;

    /**
     * Generate embedding vector for given text.
     *
     * @param text Input text to embed
     * @return float array representing the text embedding
     */
    public float[] generateEmbedding(String text) {
        if (text == null || text.trim().isEmpty()) {
            log.warn("Received empty text for embedding, returning zero vector");
            return new float[768];
        }

        long startTime = System.currentTimeMillis();
        log.debug("Generating embedding for text (length: {} chars)", text.length());

        try {
            float[] embedding = embeddingModel.embed(text);
            long duration = System.currentTimeMillis() - startTime;
            log.info("Generated embedding with {} dimensions in {}ms", embedding.length, duration);
            return embedding;
        } catch (Exception e) {
            log.error("Embedding generation failed: {}", e.getMessage(), e);
            throw new RuntimeException("Embedding generation failed", e);
        }
    }

    /**
     * Generate embeddings for multiple texts in batch.
     *
     * @param texts List of texts to embed
     * @return List of embedding vectors in same order as input
     */
    public List<float[]> generateEmbeddings(List<String> texts) {
        log.info("Generating embeddings for {} texts", texts.size());
        long startTime = System.currentTimeMillis();

        List<float[]> embeddings = texts.stream()
            .map(this::generateEmbedding)
            .collect(Collectors.toList());

        long duration = System.currentTimeMillis() - startTime;
        log.info("Generated {} embeddings in {}ms (avg: {}ms per embedding)",
            embeddings.size(), duration, embeddings.isEmpty() ? 0 : duration / embeddings.size());

        return embeddings;
    }

    /**
     * Generate embedding with retry logic for transient failures.
     *
     * @param text Text to embed
     * @param maxRetries Maximum number of retry attempts
     * @return Embedding vector
     */
    public float[] generateEmbeddingWithRetry(String text, int maxRetries) {
        int attempt = 0;
        Exception lastException = null;

        while (attempt < maxRetries) {
            try {
                return generateEmbedding(text);
            } catch (Exception e) {
                lastException = e;
                attempt++;
                if (attempt < maxRetries) {
                    long waitTime = (long) Math.pow(2, attempt) * 1000;
                    log.warn("Embedding generation failed (attempt {}/{}), retrying in {}ms",
                        attempt, maxRetries, waitTime);
                    try {
                        Thread.sleep(waitTime);
                    } catch (InterruptedException ie) {
                        Thread.currentThread().interrupt();
                        throw new RuntimeException("Interrupted during retry", ie);
                    }
                }
            }
        }

        log.error("Failed to generate embedding after {} attempts", maxRetries);
        throw new RuntimeException("Embedding generation failed after retries", lastException);
    }

    /**
     * Check if embedding service is available.
     * Gemini is a cloud service - always available if API key is configured.
     *
     * @return true always (kept for backward compatibility with callers)
     */
    public boolean isOllamaAvailable() {
        return true;
    }

    /**
     * Get the dimensionality of embeddings generated by the current model.
     * text-embedding-004 produces 768-dimensional embeddings by default.
     *
     * @return Number of dimensions
     */
    public int getEmbeddingDimensions() {
        return 768;
    }
}
