spring:
  docker:
    compose:
      enabled: false
  application:
    name: "users"
  profiles:
    active: default
  config:
    import: "optional:configserver:http://localhost:8071/" #configserver:http://configserver:8071/ #configserver:http://localhost:8071/
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: 192.168.0.101:9194
      bus:
        trace:
          enabled: true
        refresh:
          enabled: true
        env:
          enabled: true
  kafka:
    bootstrap-servers: 192.168.0.101:9194
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
      request-timeout-ms: 30000
      delivery-timeout-ms: 120000
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/ #http://eurekaserver:8070/eureka/ #http://localhost:8070/eureka/

info:
  app:
    name: "users"
    description: "User Service for finances"
    version: "1.0.0"

#minio:
#  url: http://localhost:9000
#  access-key: loki
#  secret-key: supersecret
#  bucket-name: userFiles


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

logging:
  level:
    com:
      finance:
        userservice: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"