package com.finance.userservice.constant;

public enum GroupActivityType {
    GROUP_CREATED,
    INVITE_SENT,
    INVITE_ACCEPTED,
    INVITE_REJECTED,
    ACCOUNT_LINKED,
    ACCOUNT_UNLINKED,
    MEMBER_LEFT,
    ADMIN_LEFT,
    MEMBER_INVITED,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,
    INVITATION_CANCELLED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,
    GROUP_UPDATED,
    GROUP_DELETED,
    // Planning activities
    PLANNING_CREATED,
    PLANNING_UPDATED,
    PLANNING_DELETED,
    PLANNING_BUDGET_EXCEEDED,
    PLANNING_BUDGET_COMPLETED
}
