spring:
  application:
    name: "configserver"
  profiles:
    active: git #native
  cloud:
    config:
      server:
        git:
          username: "${GIT_USERNAME}"
          password: "${GIT_PASSWORD}"
          uri: "https://github.com/BinhAn1676/FinancesConfig.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
    bus:
      enabled: true
  kafka:
    bootstrap-servers: 192.168.0.101:9194

server:
  port: 8071

encrypt:
  key: "${ENCRYPT_KEY}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    busrefresh:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
